// ============================================================
// candidatos_parlamento.js  —  Generado automáticamente
// Elecciones Generales Perú 2026 — Candidatos al Parlamento
// tipoCandidatura: 'diputado' | 'senador' | 'parlamento_andino'
// posicion_lista: completar manualmente
// ============================================================

const candidatos = [
    {
        nombre: 'Alama Gonzales Maria Rosa',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/7a7d3798-56af-4e4b-80ca-328fca24083b.jpg',
        genero: 'F',
        edad: 45,
        partido: 'AHORA NACION',
        tipoCandidatura: 'senador',
        circunscripcion: 'Amazonas',
        departamento: 'Cajamarca',
        profesion: 'No se puede determinar una profesión u ocupación principal.',
        formacion: 'No se ha alcanzado un nivel educativo universitario o superior.',
        especializacion: null,
        expPublica: 'No',
        experienciaLaboral: 'No se reporta experiencia laboral.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/36,000',
        origenIngresos: 'Sector privado',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'No declara bienes muebles',
        bio: 'Alama Gonzales Maria Rosa es una candidata al Senado por el partido Ahora Nación, sin experiencia previa en cargos de elección popular ni en cargos partidarios. No se reportan sentencias ni demandas en su historial.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/4d7386b0-f9dc-46b5-b3a0-949d892a5708.pdf',
        extranjero: false,
        millennial: false,
        movilidad: false,
        educacionGrupo: 'secundaria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Alva Davila Fortunato',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/3f9fd68e-7627-4a58-a2dd-2fe0c18e731a.jpg',
        genero: 'M',
        edad: 73,
        partido: 'AHORA NACION',
        tipoCandidatura: 'senador',
        circunscripcion: 'Único Nacional',
        departamento: 'Huancavelica',
        profesion: 'Doctor en Medio Ambiente y Desarrollo Sostenible',
        formacion: 'Cuenta con un doctorado en Medio Ambiente y Desarrollo Sostenible y una maestría en Ciencias.',
        especializacion: 'Medio Ambiente y Desarrollo Sostenible',
        expPublica: 'No',
        experienciaLaboral: 'No se reporta experiencia laboral relevante.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'Tercer suplente en el Tribunal Nacional de Ética y Disciplina de Ahora Nación.',
        continuidad: 'Renunció a Acción Popular en 2023.',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/228,837',
        origenIngresos: 'Sector público',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'Registra 1 bien mueble que sumados ascienden a S/7,000',
        bio: 'Alva Davila Fortunato es un candidato a senador por el partido Ahora Nación, con formación académica en medio ambiente y desarrollo sostenible. No ha ocupado cargos de elección popular y su trayectoria incluye roles partidarios recientes.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/7551437c-0293-4c83-b2e1-85d06dcf22e9.pdf',
        extranjero: false,
        millennial: false,
        movilidad: false,
        educacionGrupo: 'doctorado',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Graciela Alvarado Avalos',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/6bdd1edc-2d65-402f-96cc-4ea3152d467f.jpg',
        genero: 'F',
        edad: 69,
        partido: 'AHORA NACION',
        tipoCandidatura: 'senador',
        circunscripcion: 'Único Nacional',
        departamento: 'La Libertad',
        profesion: 'No se especifica profesión u ocupación principal.',
        formacion: 'No se declara formación académica universitaria o de posgrado.',
        especializacion: null,
        expPublica: 'No',
        experienciaLaboral: 'No se declara experiencia laboral.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/128,400',
        origenIngresos: 'Sector público y privado',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'No declara bienes muebles',
        bio: 'Graciela Alvarado Avalos es una candidata al Senado por el partido Ahora Nación. No presenta experiencia laboral ni formación académica universitaria.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/565da96b-7bca-4285-b493-6af1a770534a.pdf',
        extranjero: false,
        millennial: false,
        movilidad: false,
        educacionGrupo: 'secundaria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Luz Aurelia Alvarado Cáceres',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/a1bde276-6c1f-4c6d-ae48-4cecf4bd86f9.jpg',
        genero: 'F',
        edad: 73,
        partido: 'AHORA NACION',
        tipoCandidatura: 'senador',
        circunscripcion: 'Único Nacional',
        departamento: 'Ancash',
        profesion: 'Especialista en contabilidad empresarial',
        formacion: 'Cursó una especialización en contabilidad empresarial.',
        especializacion: 'Contabilidad',
        expPublica: 'No',
        experienciaLaboral: 'No se reporta experiencia laboral.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/8,410.08',
        origenIngresos: 'Sector público',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'No declara bienes muebles',
        bio: 'Luz Aurelia Alvarado Cáceres es una especialista en contabilidad empresarial que postula al cargo de senador por el partido Ahora Nación. No cuenta con experiencia laboral reportada ni con cargos de elección popular previos.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/36f206e6-58a6-4615-a913-6f614a319855.pdf',
        extranjero: false,
        millennial: false,
        movilidad: false,
        educacionGrupo: 'tecnico',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Beatriz Liliana Aguilar Cervantes',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/60d8c94d-e990-4ccf-a331-fe90b6f4cffd.jpg',
        genero: 'F',
        edad: 46,
        partido: 'AHORA NACION',
        tipoCandidatura: 'diputado',
        circunscripcion: 'Ayacucho',
        departamento: 'Ayacucho',
        profesion: 'Obstetra y especialista en gestión de salud.',
        formacion: 'Cuenta con un máster en Gobierno y Gerencia en Salud y es licenciada en Obstetricia.',
        especializacion: 'Gestión de salud',
        expPublica: 'No',
        experienciaLaboral: 'Sub Gerente de Desarrollo Social y Participación Ciudadana en la Municipalidad Distrital de Iguain.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/84,109.19',
        origenIngresos: 'Sector público',
        inmuebles: 'Registra 8 bienes inmueblees que sumados ascienden a S/765,000 <span class="asterisco-bienes"> *Estos bienes se refieren a terrenos, casas, departamentos, edificios, fábricas, estacionamientos, depósitos, etc.</span>',
        muebles: 'No declara bienes muebles',
        bio: 'Beatriz Liliana Aguilar Cervantes es una candidata a diputada por el partido Ahora Nación, con una sólida formación en obstetricia y gestión de salud. No ha ocupado cargos de elección popular ni partidarios previamente.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/6a81c462-b4b5-47d6-aaee-8a99b9519e78.pdf',
        extranjero: false,
        millennial: false,
        movilidad: true,
        educacionGrupo: 'maestria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Silvia Judith Aldana Paredes',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/b6b37ce6-7f56-45d3-b590-69c607ba7c9e.jpg',
        genero: 'F',
        edad: 40,
        partido: 'AHORA NACION',
        tipoCandidatura: 'diputado',
        circunscripcion: 'Cajamarca',
        departamento: 'Cajamarca',
        profesion: 'Licenciada en enfermería con una maestría en administración y gerencia pública.',
        formacion: 'Posee una licenciatura en enfermería y una maestría en administración y gerencia pública.',
        especializacion: 'Enfermería',
        expPublica: 'No',
        experienciaLaboral: 'No cuenta con experiencia laboral registrada.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'Renunció a Unión por el Perú en 2014 y a El Frente Amplio por Justicia, Vida y Libertad en 2021.',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/80,000',
        origenIngresos: 'Sector público y privado',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'Registra 3 bienes mueblees que sumados ascienden a S/13,600',
        bio: 'Silvia Judith Aldana Paredes es una candidata a diputada por el partido Ahora Nación, con formación en enfermería y administración pública. No ha ocupado cargos de elección popular ni partidarios.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/3675effa-9979-4898-8241-ce5ad18e8d30.pdf',
        extranjero: false,
        millennial: true,
        movilidad: false,
        educacionGrupo: 'universitario',
        inconclusos: true,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Juvenal Zereceda Vasquez',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/6c25e173-27ef-4404-b322-ae5b64fa8816.jpg',
        genero: 'M',
        edad: 61,
        partido: 'ALIANZA UNIDAD NACIONAL',
        tipoCandidatura: 'diputado',
        circunscripcion: 'Cusco',
        departamento: 'Cusco',
        profesion: 'No se puede determinar una profesión u ocupación principal.',
        formacion: 'No se dispone de información sobre su formación académica.',
        especializacion: null,
        expPublica: 'No',
        experienciaLaboral: 'No se dispone de información sobre su experiencia laboral.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'No declara ingresos',
        origenIngresos: 'No declara',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'No declara bienes muebles',
        bio: 'Juvenal Zereceda Vasquez es un candidato a diputado por el partido ALIANZA UNIDAD NACIONAL en la circunscripción de Cusco. No se dispone de información sobre su trayectoria política o experiencia laboral.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/3f78d969-639e-4b70-a0cd-29bcd964e985.pdf',
        extranjero: false,
        millennial: false,
        movilidad: false,
        educacionGrupo: 'primaria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Sumiry Yuleysi Aguilar Silva',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/e0eaa5fa-9af1-4353-9ece-30d84d304184.jpg',
        genero: 'F',
        edad: 31,
        partido: 'AHORA NACION',
        tipoCandidatura: 'diputado',
        circunscripcion: 'Ica',
        departamento: 'Cusco',
        profesion: 'Ingeniera agrónoma con especialización en suelos.',
        formacion: 'Posee un magíster en Ciencias en Suelos de la Universidad Nacional Agraria La Molina.',
        especializacion: 'Agronomía',
        expPublica: 'No',
        experienciaLaboral: 'No cuenta con experiencia laboral registrada.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/38,791.64',
        origenIngresos: 'Sector público y privado',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'Registra 1 bien mueble que sumados ascienden a S/15,000',
        bio: 'Sumiry Yuleysi Aguilar Silva es ingeniera agrónoma con un magíster en Ciencias en Suelos. Actualmente postula como diputada por el partido Ahora Nación en la región de Ica.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/598fd58c-1b68-49dc-97c7-1e023612ac87.pdf',
        extranjero: false,
        millennial: true,
        movilidad: false,
        educacionGrupo: 'maestria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Anita Mileidi Abanto Villegas',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/56f0e603-5a74-4730-bb7d-bdb19b3b4b9a.jpg',
        genero: 'F',
        edad: 28,
        partido: 'AHORA NACION',
        tipoCandidatura: 'diputado',
        circunscripcion: 'Lima Metropolitana',
        departamento: 'Cajamarca',
        profesion: 'Ingeniera económica con experiencia en análisis y finanzas.',
        formacion: 'Egresada de la Universidad Nacional de Ingeniería en Ingeniería Económica.',
        especializacion: null,
        expPublica: 'No',
        experienciaLaboral: 'Gerenta en Independiente es su cargo más reciente.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/38,000',
        origenIngresos: 'Sector privado',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'No declara bienes muebles',
        bio: 'Anita Mileidi Abanto Villegas es una ingeniera económica que ha trabajado en diversas posiciones en el sector privado. Actualmente postula como diputada por el partido Ahora Nación en Lima Metropolitana.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/c9949abb-c15f-4dda-9854-1df867564c03.pdf',
        extranjero: false,
        millennial: false,
        movilidad: false,
        educacionGrupo: 'universitario',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Claudio Iván Zegarra Arellano',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/0acddbf0-98fb-448f-aae4-94b332058293.jpg',
        genero: 'M',
        edad: 57,
        partido: 'ALIANZA UNIDAD NACIONAL',
        tipoCandidatura: 'diputado',
        circunscripcion: 'Lima Metropolitana',
        departamento: 'Lima',
        profesion: 'No se puede determinar una profesión u ocupación principal.',
        formacion: 'No se dispone de información sobre su formación académica.',
        especializacion: null,
        expPublica: 'No',
        experienciaLaboral: 'No se dispone de información sobre su experiencia laboral.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'No declara ingresos',
        origenIngresos: 'No declara',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'No declara bienes muebles',
        bio: 'Claudio Iván Zegarra Arellano es un candidato a diputado por el partido ALIANZA UNIDAD NACIONAL en Lima Metropolitana. No se dispone de información sobre su trayectoria política o experiencia laboral.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/4e35543d-b778-4714-8b03-b0127d7672c2.pdf',
        extranjero: false,
        millennial: false,
        movilidad: false,
        educacionGrupo: 'primaria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Gloria Dayana Yañez Alejandro',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/e995e4d1-2407-4bc3-9a9b-81189d7eb422.jpg',
        genero: 'F',
        edad: 32,
        partido: 'AHORA NACION',
        tipoCandidatura: 'diputado',
        circunscripcion: 'Lima Metropolitana',
        departamento: 'Lima',
        profesion: 'Gestora pública con maestría en gestión pública.',
        formacion: 'Posee una maestría en gestión pública de la Universidad Nacional Mayor de San Marcos.',
        especializacion: null,
        expPublica: 'No',
        experienciaLaboral: 'No tiene experiencia laboral registrada.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/8,400',
        origenIngresos: 'Sector privado',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'No declara bienes muebles',
        bio: 'Gloria Dayana Yañez Alejandro es candidata a diputada por el partido Ahora Nación. Tiene una maestría en gestión pública y no cuenta con experiencia laboral registrada.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/ae69636a-05d2-4296-806d-329e46e6ee47.pdf',
        extranjero: false,
        millennial: true,
        movilidad: false,
        educacionGrupo: 'secundaria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Alama Gonzales Maria Rosa',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/7a7d3798-56af-4e4b-80ca-328fca24083b.jpg',
        genero: 'F',
        edad: 45,
        partido: 'AHORA NACION',
        tipoCandidatura: 'parlamento_andino',
        circunscripcion: 'Amazonas',
        departamento: 'Cajamarca',
        profesion: 'No se puede determinar una profesión u ocupación principal.',
        formacion: 'No se ha alcanzado un nivel educativo universitario o superior.',
        especializacion: null,
        expPublica: 'No',
        experienciaLaboral: 'No se reporta experiencia laboral.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/36,000',
        origenIngresos: 'Sector privado',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'No declara bienes muebles',
        bio: 'Alama Gonzales Maria Rosa es una candidata al Senado por el partido Ahora Nación, sin experiencia previa en cargos de elección popular ni en cargos partidarios. No se reportan sentencias ni demandas en su historial.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/4d7386b0-f9dc-46b5-b3a0-949d892a5708.pdf',
        extranjero: false,
        millennial: false,
        movilidad: false,
        educacionGrupo: 'secundaria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Gloria Dayana Yañez Alejandro',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/e995e4d1-2407-4bc3-9a9b-81189d7eb422.jpg',
        genero: 'F',
        edad: 32,
        partido: 'AHORA NACION',
        tipoCandidatura: 'parlamento_andino',
        circunscripcion: 'Lima Metropolitana',
        departamento: 'Lima',
        profesion: 'Gestora pública con maestría en gestión pública.',
        formacion: 'Posee una maestría en gestión pública de la Universidad Nacional Mayor de San Marcos.',
        especializacion: null,
        expPublica: 'No',
        experienciaLaboral: 'No tiene experiencia laboral registrada.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/8,400',
        origenIngresos: 'Sector privado',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'No declara bienes muebles',
        bio: 'Gloria Dayana Yañez Alejandro es candidata a diputada por el partido Ahora Nación. Tiene una maestría en gestión pública y no cuenta con experiencia laboral registrada.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/ae69636a-05d2-4296-806d-329e46e6ee47.pdf',
        extranjero: false,
        millennial: true,
        movilidad: false,
        educacionGrupo: 'secundaria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Sumiry Yuleysi Aguilar Silva',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/e0eaa5fa-9af1-4353-9ece-30d84d304184.jpg',
        genero: 'F',
        edad: 31,
        partido: 'AHORA NACION',
        tipoCandidatura: 'parlamento_andino',
        circunscripcion: 'Ica',
        departamento: 'Cusco',
        profesion: 'Ingeniera agrónoma con especialización en suelos.',
        formacion: 'Posee un magíster en Ciencias en Suelos de la Universidad Nacional Agraria La Molina.',
        especializacion: 'Agronomía',
        expPublica: 'No',
        experienciaLaboral: 'No cuenta con experiencia laboral registrada.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/38,791.64',
        origenIngresos: 'Sector público y privado',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'Registra 1 bien mueble que sumados ascienden a S/15,000',
        bio: 'Sumiry Yuleysi Aguilar Silva es ingeniera agrónoma con un magíster en Ciencias en Suelos. Actualmente postula como diputada por el partido Ahora Nación en la región de Ica.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/598fd58c-1b68-49dc-97c7-1e023612ac87.pdf',
        extranjero: false,
        millennial: true,
        movilidad: false,
        educacionGrupo: 'maestria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Beatriz Liliana Aguilar Cervantes',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/60d8c94d-e990-4ccf-a331-fe90b6f4cffd.jpg',
        genero: 'F',
        edad: 46,
        partido: 'AHORA NACION',
        tipoCandidatura: 'parlamento_andino',
        circunscripcion: 'Ayacucho',
        departamento: 'Ayacucho',
        profesion: 'Obstetra y especialista en gestión de salud.',
        formacion: 'Cuenta con un máster en Gobierno y Gerencia en Salud y es licenciada en Obstetricia.',
        especializacion: 'Gestión de salud',
        expPublica: 'No',
        experienciaLaboral: 'Sub Gerente de Desarrollo Social y Participación Ciudadana en la Municipalidad Distrital de Iguain.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/84,109.19',
        origenIngresos: 'Sector público',
        inmuebles: 'Registra 8 bienes inmueblees que sumados ascienden a S/765,000 <span class="asterisco-bienes"> *Estos bienes se refieren a terrenos, casas, departamentos, edificios, fábricas, estacionamientos, depósitos, etc.</span>',
        muebles: 'No declara bienes muebles',
        bio: 'Beatriz Liliana Aguilar Cervantes es una candidata a diputada por el partido Ahora Nación, con una sólida formación en obstetricia y gestión de salud. No ha ocupado cargos de elección popular ni partidarios previamente.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/6a81c462-b4b5-47d6-aaee-8a99b9519e78.pdf',
        extranjero: false,
        millennial: false,
        movilidad: true,
        educacionGrupo: 'maestria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },

    {
        nombre: 'Graciela Alvarado Avalos',
        fotoCandidato: 'https://mpesije.jne.gob.pe/apidocs/6bdd1edc-2d65-402f-96cc-4ea3152d467f.jpg',
        genero: 'F',
        edad: 69,
        partido: 'AHORA NACION',
        tipoCandidatura: 'parlamento_andino',
        circunscripcion: 'Único Nacional',
        departamento: 'La Libertad',
        profesion: 'No se especifica profesión u ocupación principal.',
        formacion: 'No se declara formación académica universitaria o de posgrado.',
        especializacion: null,
        expPublica: 'No',
        experienciaLaboral: 'No se declara experiencia laboral.',
        expInternacional: 'No',
        cargosEleccion: 'No',
        cargosPartidarios: 'No declara cargos partidarios',
        continuidad: 'No se declara militancia previa distinta a la actual',
        sentencias: 'No declara sentencias',
        demandas: 'Declara no tener demandas',
        ingresos: 'S/128,400',
        origenIngresos: 'Sector público y privado',
        inmuebles: 'No declara bienes inmuebles',
        muebles: 'No declara bienes muebles',
        bio: 'Graciela Alvarado Avalos es una candidata al Senado por el partido Ahora Nación. No presenta experiencia laboral ni formación académica universitaria.',
        pdfLink: 'https://mpesije.jne.gob.pe/apidocs/565da96b-7bca-4285-b493-6af1a770534a.pdf',
        extranjero: false,
        millennial: false,
        movilidad: false,
        educacionGrupo: 'secundaria',
        inconclusos: false,
        delitos: false,
        reincidencia: false,
        sentenciaTipo: null,
        tipoDelito: null,
        detalles: null,
        fallo: null,
        informacion: null,
        acciones: null,
        posicion_lista: null,
    },
];
